### PR TITLE
Fix configure.ac to build with OpenSSL 1.1.

### PR DESCRIPTION
**Pull request by thijskh**
I have not run autoreconf, if you want this to be part of the PR let me know.

### CODE REVIEW

**Comment by dhawes** [comment]
I'm fairly certain line 134 can be removed completely. SSL_library_init hasn't been used since we started using libcurl, which was in 2010.

After removing that line there are some warnings we will need to clean up to fully support OpenSSL 1.1.

**Comment by thijskh** [comment]
I've updated the PR to remove said line.

The warnings are the following:
```
mod_auth_cas.c: In function 'cas_cleanup':
mod_auth_cas.c:2560:35: warning: the comparison will always evaluate as 'false' for the address of 'cas_ssl_locking_callback' will never be NULL [-Waddress]
  if(CRYPTO_get_locking_callback() == cas_ssl_locking_callback)
                                   ^~
mod_auth_cas.c:2561:36: warning: suggest braces around empty body in an 'if' statement [-Wempty-body]
   CRYPTO_set_locking_callback(NULL);
                                    ^
mod_auth_cas.c:2566:36: warning: the comparison will always evaluate as 'false' for the address of 'cas_ssl_id_callback' will never be NULL [-Waddress]
  if(CRYPTO_THREADID_get_callback() == cas_ssl_id_callback)
                                    ^~
```

**Comment by thijskh** [comment]
Can this be merged? Anything against merging it?

**Comment by dhawes** [comment]
No real objections, but I'd like to see those warnings cleaned up now that we've identified them. I'll put it on my list of things to look at.

**Comment by adaugherity** [comment]
Please merge this -- it will fix building on recent distros which ship OpenSSL 1.1 (more and more of them nowadays), and shouldn't hurt anything for older OpenSSL.  Cleanup for the warnings and/or other OpenSSL 1.1 issues shouldn't be forgotten, but I hope that could be tracked in a separate issue rather than blocking this merge.

FYI, here is the [definition of the CRYPTO_*_callback compatibility macros](https://github.com/openssl/openssl/blob/7d38ca3f8bca58bf7b69e78c1f1ab69e5f429dff/include/openssl/crypto.h#L207-L222); to build in "pure 1.1" mode, set OPENSSL_API_COMPAT accordingly, e.g. `./configure CFLAGS="-DOPENSSL_API_COMPAT=0x10100000L"` (the default value is 0, i.e. widest compatibility).

Besides turning those warnings into errors, building that way also errors on CRYPTO_THREADID and CRYPTO_LOCK, which are apparently related to these callbacks.

Thanks!

**Comment by dhawes** [comment]
My first stab at cleaning up the warnings is at:

https://github.com/dhawes/mod_auth_cas/tree/merge-request-118

If you could test both OpenSSL 1.1 and OpenSSL < 1.1, that would be helpful for getting this merged.

**Comment by adaugherity** [comment]
That branch builds without openssl warnings with a default `./configure` on openssl 1.1; however if I build with OPENSSL_API_COMPAT set to 1.1 as described above (dropping deprecated APIs), one error remains:
```
In file included from mod_auth_cas.c:72:0:
mod_auth_cas.h:215:26: error: unknown type name ‘CRYPTO_THREADID’; did you mean ‘CRYPTO_THREAD_ID’?
 void cas_ssl_id_callback(CRYPTO_THREADID *id);
                          ^~~~~~~~~~~~~~~
                          CRYPTO_THREAD_ID
```
Probably that section of mod_auth_cas.h needs to be wrapped in an openssl version check like you did in mod_auth_cas.c.

**Comment by dhawes** [comment]
Yeah, good catch. Fix pushed to my branch.

**Comment by dhawes** [comment]
Merged in #155.

**Comment by adaugherity** [comment]
This is a little late, especially since the other PR has now been merged, but since you asked for testing on multiple openssl versions, FYI: I have been building git checkouts against all currently-supported SUSE distros in my home dir in the openSUSE Build Service ([project page](https://build.opensuse.org/package/show/home:adaugherity/apache2-mod_auth_cas); [RPM download](
https://software.opensuse.org//download.html?project=home%3Aadaugherity&package=apache2-mod_auth_cas)).

This covers a wide range of Apache and OpenSSL versions, which all build without any issues:
* apache 2.2.34/openssl 0.9.8j (SLES 11 SP4)
* apache 2.4.23/openssl 1.0.2j (SLES 12 SP3/Leap 42.3)
* apache 2.4.33/openssl 1.1.0i (SLES/Leap 15.0)

Once you make a new release I'll try to get the package submitted to a more standard OBS repo, and maybe eventually the standard openSUSE repo itself.
