### PR TITLE
Bump required APR versions

### LINKED ISSUE #173: mod_auth_cas fails to build against CentOS/RHEL 7 Apache
When building against the latest git clone of mod_auth_cas the build fails as can be seen below.  If I git clone -b 'v1.2' the version builds just fine.

make[2]: Entering directory `/tmp/mod_auth_cas/src'
/usr/bin/apxs -c -lpcre -lcrypto  -Wc," -D_LARGEFILE64_SOURCE -g -O2 -Wall -Wextra -Wdeclaration-after-statement -Wformat -Wformat-security -Wmissing-declarations -Wno-unused-parameter -Wpointer-arith -Wstrict-prototypes " -Wl,"  -lcurl   -lpcre -lcrypto " mod_auth_cas.c cas_saml_attr.c
/usr/lib64/apr-1/build/libtool --silent --mode=compile gcc -std=gnu99 -prefer-pic -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic  -DLINUX -D_REENTRANT -D_GNU_SOURCE -pthread -I/usr/include/httpd  -I/usr/include/apr-1   -I/usr/include/apr-1   -D_LARGEFILE64_SOURCE -g -O2 -Wall -Wextra -Wdeclaration-after-statement -Wformat -Wformat-security -Wmissing-declarations -Wno-unused-parameter -Wpointer-arith -Wstrict-prototypes   -c -o mod_auth_cas.lo mod_auth_cas.c && touch mod_auth_cas.slo
mod_auth_cas.c:49:24: fatal error: apr_escape.h: No such file or directory
 #include "apr_escape.h"
                        ^
compilation terminated.
apxs:Error: Command failed with rc=65536
.
make[2]: Leaving directory `/tmp/mod_auth_cas/src'
make[2]: *** [mod_auth_cas.la] Error 1
make[1]: Leaving directory `/tmp/mod_auth_cas'
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
The command '/bin/sh -c cd /tmp && git clone https://github.com/apereo/mod_auth_cas.git &&     cd /tmp/mod_auth_cas &&     autoreconf -ivf  &&     ./configure &&     make && make install' returned a non-zero code: 2

### PR DESCRIPTION
**Pull request by dhawes**
Fixes #173

### CODE REVIEW

**Comment by agilis1** [comment]
I have been trying to get mod_auth_cas v1.2 to work with CentOS 7's 2.4.6 version of Apache and I followed @dhawes instructions in #173  When I did these steps, I compiled APR v1.7 and mod_auth_cas v1.2 and from what I can tell, everything compiled from source correctly.

I configured /etc/sysconfig/httpd so that the following is at the bottom of the file:
LD_LIBRARY_PATH=/usr/local/apr/lib

I verified /usr/local/apr/lib has the APR libraries.

When I run httpd -V the following is outputted:

Server version: Apache/2.4.6 (CentOS)
Server built: Apr 2 2020 13:13:23
Server's Module Magic Number: 20120211:24
Server loaded: APR 1.4.8, APR-UTIL 1.5.2
Compiled using: APR 1.4.8, APR-UTIL 1.5.2
Architecture: 64-bit
Server MPM: prefork

I cannot get httpd to use APR 1.7.

Could anyone that was successful tell me why this is not working on my end?
